# Generated by Django 5.0.2 on 2024-03-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cake_occasion_object_cake_occasion_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakevarient',
            old_name='Category_object',
            new_name='cakecategory',
        ),
    ]
