# Generated by Django 5.0.2 on 2024-03-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_category_object_cakevarient_cakecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occasion',
            old_name='Occasion',
            new_name='occasion',
        ),
    ]
